Repository vegaprotocol/specs, pull requests merged in 2022-12, with the labels that each got.

#1334 User interface: `MORD` manage orders: add first mord acs
  user-interface/7003-MORD-manage_orders.md
  user-interface/README.md
Labels: front-end-ac

#1300 User interface: `WITH` Withdrawals
  user-interface/0004-EWAL-connect_ethereum_wallet.md
  user-interface/0005-ETXN-submit_ethereum_transaction.md
  user-interface/1002-WITH-withdraw.md
  user-interface/9001-DATA-data_display.md
  user-interface/README.md
Labels: front-end-ac

#1447 chore: Amend acceptance criteria numbers to remove duplicates
  protocol/0076-DANO-data-node.md
Labels: ac-code-remediation

#1472 feat: update AC 0003-015
  protocol/0052-FPOS-fractional_orders_positions.md
Labels: ac-code-remediation

#1443 Update 0061-REWP-pos_rewards.md
  protocol/0061-REWP-pos_rewards.md
Labels: ac-code-remediation

#1420 Update 0057-TRAN-transfers.md
  protocol/0057-TRAN-transfers.md
Labels: ac-code-remediation

#1434 Update 0069-VCBS-validators_chosen_by_stake.md
  protocol/0069-VCBS-validators_chosen_by_stake.md
Labels: ac-code-remediation

#1476 chore: ACs for market change proposal parameter changes
  protocol/0028-GOVE-governance.md
Labels: ac-code-remediation

#1474 Update 0062-SPAM-spam_protection.md
  protocol/0062-SPAM-spam_protection.md
Labels: ac-code-remediation

#1481 Bring spec in line with implemented scaling of liquidity fees
  protocol/0038-OLIQ-liquidity_provision_order_type.md
  protocol/0042-LIQF-setting_fees_and_rewarding_lps.md
Labels: spec-improvement

#1478 fix: remove AC checkboxes from the spec
  protocol/0038-OLIQ-liquidity_provision_order_type.md
Labels: ac-code-remediation

#1479 fix: duplicate AC code in spec
  protocol/0057-TRAN-transfers.md
Labels: ac-code-remediation
