Repository vegaprotocol/specs, pull requests merged in 2022-08, with the labels that each got.

#1162 Spec clarifiaction
  protocol/0021-MDAT-market_data_spec.md
  protocol/0032-PRIM-price_monitoring.md
Labels: spec-improvement

#1140 Update 0016-PFUT-product_builtin_future.md
  protocol/0016-PFUT-product_builtin_future.md
Labels: ac-code-remediation

#1170 fix: incorrect AC code format
  protocol/0013-ACCT-accounts.md
Labels: ac-code-remediation

#1183 Removed explicit partyID argument
  protocol/0033-OCAN-cancel_orders.md
Labels: enhancement

#1169 chore: update links and AC codes
  protocol/0040-ASSF-asset_framework.md
Labels: ac-code-remediation

#1180 Liquidity auction at end-of-block spec
  protocol/0035-LIQM-liquidity_monitoring.md
Labels: liquidity, ac-code-remediation

#1179 Batch Instruction spec
  protocol/0074-BTCH-batch-market-instructions.md
Labels: specs, improvement

#1175 fix: rename els to growth adjusted LP share
  non-protocol-specs/0011-NP-DANO-data-node.md
  protocol/0028-GOVE-governance.md
  protocol/0038-OLIQ-liquidity_provision_order_type.md
  protocol/0042-LIQF-setting_fees_and_rewarding_lps.md
  protocol/0044-LIME-lp_mechanics.md
Labels: spec-improvement

#1196 fix: broken link to feature file
  protocol/0016-PFUT-product_builtin_future.md
Labels: ac-code-remediation

#1206 fix: opening auction volume shouldn't set the whole 0th period volume
  protocol/0042-LIQF-setting_fees_and_rewarding_lps.md
Labels: spec-bug
