Repository vegaprotocol/specs, pull requests merged in 2022-09, with the labels that each got.

#1231 Update 0009-NP-SNAP-snapshots.md Post QA Review
  non-protocol-specs/0009-NP-SNAP-snapshots.md
Labels: ac-code-remediation

#1233 chore: make 016 AC for a later milestone
  protocol/0045-DSRC-data_sourcing.md
Labels: ac-code-remediation

#1226 0069-VCBS-validators_chosen_by_stake.md Post QA review
  protocol/0069-VCBS-validators_chosen_by_stake.md
Labels: ac-code-remediation

#1228 0028-GOVE-governance.md Post QA Review
  protocol/0028-GOVE-governance.md
Labels: ac-code-remediation

#1230 Update 0047-DSRF-data_source_filter.md Post QA Review
  protocol/0047-DSRF-data_source_filter.md
Labels: ac-code-remediation

#1236 Update 0047-DSRF-data_source_filter.md
  protocol/0047-DSRF-data_source_filter.md
Labels: ac-code-remediation

#1238 fix: suggested AC
  protocol/0045-DSRC-data_sourcing.md
Labels: specs

#1205 Add AC-28 for 0073-LIMN spec.
  protocol/0073-LIMN-limited_network_life.md
Labels: ac-code-remediation

#1247 Update 0074-BTCH-batch-market-instructions.md
  protocol/0074-BTCH-batch-market-instructions.md
Labels: spec-improvement

#1213 Update 0071-STAK-erc20_governance_token_staking.md
  protocol/0071-STAK-erc20_governance_token_staking.md
Labels: ac-code-remediation

#1181 User interface acceptance criteria: Submit order (with prerequisites)
  user-interface/0001-WALL-wallet.md
  user-interface/0002-WCON-connect_vega_wallet.md
  user-interface/0003-WTXN-submit_vega_transaction.md
  user-interface/6001-SORD-submit_orders.md
  user-interface/7001-DATA-data_display.md
  user-interface/README.md
Labels: ac-code-remediation, front-end-ac

#1128 Update 0069-VCBS-validators_chosen_by_stake.md
  protocol/0069-VCBS-validators_chosen_by_stake.md
Labels: ac-code-remediation

#1250 add AC in 0011 Check Order Allocate Margin
  protocol/0011-MARA-check_order_allocate_margin.md
Labels: ac-code-remediation

#1252 fix: add two ACs specifically testing for 0 stake to ccy siskas
  protocol/0044-LIME-lp_mechanics.md
Labels: ac-code-remediation

#1256 Update 0012-POSR-position_resolution.md
  protocol/0012-POSR-position_resolution.md
Labels: spec-improvement

#1239 feat: add additional ACs for datanode
  non-protocol-specs/0011-NP-DANO-data-node.md
Labels: requires-engineering, ac-code-remediation

#1253 Update 0064-VALP-validator_performance_based_rewards.md
  protocol/0064-VALP-validator_performance_based_rewards.md
Labels: ac-code-remediation

#1261 chore: add decimals acs to bond slashing
  protocol/0044-LIME-lp_mechanics.md
Labels: ac-code-remediation

#1265 fix: Minor changes to acceptance criteria based on discussions
  protocol/0022-AUTH-auth.md
Labels: ac-code-remediation

#1255 chore: add more ACs for ethereum key rotation
  protocol/0067-KEYS-key_management.md
Labels: ac-code-remediation

#1266 PM spec update: cover paramter updates
  protocol/0032-PRIM-price_monitoring.md
Labels: ac-code-remediation

#1263 User interface: Add placeholder for all known ACs and Categories
  protocol/categories.json
  user-interface/0001-WALL-wallet.md
  user-interface/0002-WCON-connect_vega_wallet.md
  user-interface/0003-WTXN-submit_vega_transaction.md
  user-interface/0004-EWAL-connect_ethereum_wallet.md
  user-interface/0005-ETXN-submit_ethereum_transaction.md
  user-interface/0006-NETW-network-and-nodes.md
  user-interface/1001-DEPO-desposit.md
  user-interface/1002-WITH-withdraw.md
  user-interface/1003-TRAN-transfer.md
  user-interface/1004-ASSO-associate.md
  user-interface/1005-VEST-vesting.md
  user-interface/2001-STKE-staking.md
  user-interface/2002-SINC-staking-income.md
  user-interface/3001-VOTE-vote.md
  user-interface/3002-PROP-propose.md
  user-interface/3003-PMAN-propose_new_market.md
  user-interface/3004-PMAC-propose_market_change.md
  user-interface/3005-PASN-propose_new_asset.md
  user-interface/3006-PASC-propose_asset_change.md
  user-interface/3007-PNEC-propose_network.md
  user-interface/3008-PFRO-propose_freeform.md
  user-interface/4001-TRES-view_treasury_rewards.md
  user-interface/5001-LIQF-liquidity_opportunities.md
  user-interface/5002-LIQP-provide_liquidity.md
  user-interface/5003-LIQI-liquidity_income.md
  user-interface/6000-COLL-collateral.md
  user-interface/6001-MARK-find_markets.md
  user-interface/6002-MDET-market-details.md
  user-interface/6003-ORDB-order_book.md
  user-interface/6004-PHIS-price_history.md
  user-interface/6005-THIS-trade_history.md
  user-interface/7001-COLL-collateral.md
  user-interface/7002-SORD-submit_orders.md
  user-interface/7003-MORD-manage_orders.md
  user-interface/7004-POSI-positions.md
  user-interface/7005-FILL-fills.md
  user-interface/7006-FEES-fees.md
  user-interface/8001-BLOX-transaction_and_blocks.md
  user-interface/DATA-data_display.md
  user-interface/README.md
  user-interface/apps.json
  user-interface/categories.json
Labels: front-end-ac
