Repository vegaprotocol/specs, pull requests merged in 2022-10, with the labels that each got.

#1305 User interface: remove ACs for things that are not musts
  user-interface/0001-WALL-wallet.md
  user-interface/0002-WCON-connect_vega_wallet.md
  user-interface/0003-WTXN-submit_vega_transaction.md
Labels: front-end-ac

#1262 User interface: check market status when submitting order `SORD`
  user-interface/7002-SORD-submit_orders.md
Labels: front-end-ac

#1287 Added more ACs for market depth
  protocol/0039-MKTD-market_depth_calculation.md
Labels: enhancement, DatanodeV2

#1306 Update ACs in 0007 to cover PnL test
  protocol/0007-POSN-non_core_positions_api.md
Labels: ac-code-remediation

#1310 chore: Re number acceptance criteria to remove duplicate
  protocol/0069-VCBS-validators_chosen_by_stake.md
Labels: ac-code-remediation

#1308 user-interface: SORD: amend some priorities, remove some unused codes
  user-interface/7002-SORD-submit_orders.md
Labels: front-end-ac

#1312 chore: clarify master-key AC's
  protocol/0063-VALK-validator_vega_master_keys.md
Labels: spec-improvement, ac-code-remediation

#1318 chore: move 001 AC out as not implemented
  protocol/0009-MRKP-mark_price.md
Labels: ac-code-remediation

#1320 0041 typo
  protocol/0041-TSTK-target_stake.md
Labels: specs

#1323 Remove 0004 AC
  protocol/0004-AMND-amends.md
Labels: ac-code-remediation

#1328 0070 AC for negative position decimal
  protocol/0001-MKTF-market_framework.md
  protocol/0003-MTMK-mark_to_market_settlement.md
  protocol/0004-AMND-amends.md
  protocol/0006-POSI-positions_core.md
  protocol/0019-MCAL-margin_calculator.md
  protocol/0028-GOVE-governance.md
  protocol/0029-FEES-fees.md
Labels: ac-code-remediation

#1335 User interface/better categories
  user-interface/6000-COLL-collateral.md
  user-interface/apps.json
  user-interface/categories.json
Labels: front-end-ac

#1332 fix: add signers details to data source description
  protocol/0045-DSRC-data_sourcing.md
  protocol/0046-DSRM-data_source_signed_message.md
Labels: spec-improvement, oracles

#1340 test: tiny update to wording of delete wallet
  user-interface/0001-WALL-wallet.md
Labels: front-end-ac

#1336 feat: datanode decentralized history
  protocol/0076-DANO-data-node.md
Labels: ac-code-remediation

#1357 Add AC for Negative pdp (position decimal places)
  protocol/0003-MTMK-mark_to_market_settlement.md
  protocol/0019-MCAL-margin_calculator.md
Labels: ac-code-remediation

#1285 chore: remove old datanode spec and update ACs
  non-protocol-specs/0004-NP-APIN-api_node.md
  protocol/0076-DANO-data-node.md
Labels: ac-code-remediation
