Repository vegaprotocol/specs, pull requests merged in 2022-11, with the labels that each got.

#1372 Update 0027-ASSP-asset_proposal.md
  protocol/0027-ASSP-asset_proposal.md
Labels: ac-code-remediation

#1221 0066-VALW-validator_tendermint_weights - post review new test coverage
  protocol/0066-VALW-validator_tendermint_weights.md
Labels: ac-code-remediation

#1378 correct the typo in 0011-AC-005
  protocol/0011-MARA-check_order_allocate_margin.md
Labels: ac-code-remediation

#1377 chore: add new category spec 0078-NWLI
  protocol/categories.json
Labels: ac-code-remediation

#1369 test: update ACs for system tests
  protocol/0030-ETHM-multisig_control_spec.md
  protocol/0031-ETHB-ethereum_bridge_spec.md
Labels: ac-code-remediation

#1391 Update risk parameter validation range in 0028-GOVE-governance.md
  protocol/0028-GOVE-governance.md
Labels: spec-improvement, ac-code-remediation

#1400 refactor: modify AC to reflect current implementation
  protocol/0042-LIQF-setting_fees_and_rewarding_lps.md
Labels: ac-code-remediation

#1414 chore: add ACs for 0045-DSRC-data_sourcing.md
  protocol/0048-DSRI-data_source_internal.md
  protocol/categories.json
Labels: ac-code-remediation

#1301 User interface: Associating, Staking, Staking income, and Vesting
  user-interface/1004-ASSO-associate.md
  user-interface/1005-VEST-vesting.md
  user-interface/2001-STKE-staking.md
  user-interface/2002-SINC-staking-income.md
  user-interface/README.md
Labels: front-end-ac

#1302 User interface: Governance (all)
  protocol/categories.json
  user-interface/3001-VOTE-vote.md
  user-interface/3002-PROP-propose.md
  user-interface/3003-PMAN-propose_new_market.md
  user-interface/3004-PMAC-propose_market_change.md
  user-interface/3005-PASN-propose_new_asset.md
  user-interface/3006-PASC-propose_asset_change.md
  user-interface/3007-PNEC-propose_network.md
  user-interface/3008-PFRO-propose_freeform.md
  user-interface/README.md
Labels: front-end-ac

#1418 chore: correct AC code number 0027-ASSP-020
  protocol/0027-ASSP-asset_proposal.md
Labels: ac-code-remediation

#1424 fix: poorly tagged ACs
  protocol/0027-ASSP-asset_proposal.md
Labels: ac-code-remediation

#1423 refactor: more ACs for 0038-OLIQ
  protocol/0038-OLIQ-liquidity_provision_order_type.md
Labels: ac-code-remediation

#1417 Add ACs for market behaviour after parameter changes
  protocol/0010-MARG-margin_orchestration.md
  protocol/0029-FEES-fees.md
  protocol/0035-LIQM-liquidity_monitoring.md
  protocol/0056-REWA-rewards_overview.md
Labels: ac-code-remediation

#1435 chore: Remove no longer valid OPEG AC
  protocol/0037-OPEG-pegged_orders.md
Labels: ac-code-remediation

#1445 chore: Remove performance requirement for datanode
  protocol/0076-DANO-data-node.md
Labels: ac-code-remediation

#1438 Rework OLIQ and LP rewards so we don't have exploding volumes because of prob of trading scaling
  protocol/0034-PROB-prob_weighted_liquidity_measure.ipynb
  protocol/0038-OLIQ-liquidity_provision_order_type.md
  protocol/0042-LIQF-setting_fees_and_rewarding_lps.md
  protocol/0044-LIME-lp_mechanics.md
Labels: discussion, liquidity

#1436 chore: update DSRI AC to match the intention
  protocol/0048-DSRI-data_source_internal.md
Labels: ac-code-remediation
