Repository vegaprotocol/specs, pull requests merged in 2023-01, with the labels that each got.

#1487 Remove never raised error AC
  protocol/0024-OSTA-order_status.md
Labels: ac-code-remediation

#1499 Added Acs to. 0062-SPAM
  protocol/0062-SPAM-spam_protection.md
Labels: ac-code-remediation

#1507 fix: correct duplicate AC codes
  protocol/0069-VCBS-validators_chosen_by_stake.md
Labels: ac-code-remediation

#1508 Update 0062-SPAM-spam_protection.md
  protocol/0062-SPAM-spam_protection.md
Labels: ac-code-remediation

#1517 fix: duplicated AC code in SPAM spec
  protocol/0062-SPAM-spam_protection.md
Labels: ac-code-remediation

#1519 feat: Add more protocol upgrade ACs to cover some checks on data span…
  protocol/0075-PLUP_protocol_upgrades.md
Labels: ac-code-remediation

#1516 User interface: `DEPO` Deposits
  user-interface/1001-DEPO-desposit.md
  user-interface/9001-DATA-data_display.md
  user-interface/README.md
Labels: front-end-ac

#1477 Create 0011-NP-CLIE-client-interaction-tests
  non-protocol-specs/0011-NP-CLIE-client-interaction-tests.md
  protocol/categories.json
Labels: ac-code-remediation

#1518 fix: update 0069-VCBS-058 and 0069-VCBS-054
  protocol/0069-VCBS-validators_chosen_by_stake.md
Labels: ac-code-remediation

#1527 Update 0015-INSR-market_insurance_pool_collateral.md
  protocol/0015-INSR-market_insurance_pool_collateral.md
Labels: ac-code-remediation

#1528 fix: duplicated AC codes
  protocol/0069-VCBS-validators_chosen_by_stake.md
Labels: ac-code-remediation

#1532 feat: Add two new ACs for updating the multisig contract for new vali…
  protocol/0069-VCBS-validators_chosen_by_stake.md
Labels: ac-code-remediation

#1536 fix: duplicate AC codes in 0069-VCBS
  protocol/0069-VCBS-validators_chosen_by_stake.md
Labels: ac-code-remediation

#1529 refactor: let max OI drop during auction
  protocol/0041-TSTK-target_stake.md
Labels: spec-improvement

#1534 fix: bring market.liquidity.targetstake.triggering.ratio in line with…
  protocol/0035-LIQM-liquidity_monitoring.md
Labels: ac-code-remediation

#1537 fix: duplicate AC codes in 0069-VCBS (#1536)
  protocol/0069-VCBS-validators_chosen_by_stake.md
Labels: ac-code-remediation

#1530 chore: remove untestable AC from 0018
  protocol/0018-RSKM-quant_risk_models.ipynb
Labels: ac-code-remediation

#1541 fix AC numbering on 0035-LIQM-liquidity_monitoring.md
  protocol/0035-LIQM-liquidity_monitoring.md
Labels: ac-code-remediation
