Repository vegaprotocol/specs, pull requests merged in 2023-02, with the labels that each got.

#1549 fix: Update acceptance criteria to correctly reflect implementation
  protocol/0076-DANO-data-node.md
Labels: ac-code-remediation

#1569 feat: update 0042, LP fee Transfer and Distribution (AC 0042-LIQF-018)
  protocol/0042-LIQF-setting_fees_and_rewarding_lps.md
Labels: specs, spec-improvement

#1572 feat: update maker fee transfer account
  protocol/0029-FEES-fees.md
Labels: specs, spec-improvement

#1574 Update 0048-DSRI-data_source_internal.md
  protocol/0048-DSRI-data_source_internal.md
Labels: ac-code-remediation

#1566 fix: update wording for AC 0059-VCBS-016-
  protocol/0059-STKG-simple_staking_and_delegating.md
Labels: ac-code-remediation

#1565 Update 0069-VCBS-validators_chosen_by_stake.md
  protocol/0069-VCBS-validators_chosen_by_stake.md
Labels: ac-code-remediation

#1586 chore: Remove untestable acceptance criteria - 0076-DANO-018
  protocol/0076-DANO-data-node.md
Labels: ac-code-remediation

#1594 feat: add AC for closeout API
  protocol/0007-POSN-non_core_positions_api.md
Labels: ac-code-remediation

#1597 feat: update formula in spec 0019-MCAL-margin_calculator.md line 140
  protocol/0019-MCAL-margin_calculator.md
Labels: spec-improvement

#1598 Update 0042-LIQF-setting_fees_and_rewarding_lps.md
  protocol/0042-LIQF-setting_fees_and_rewarding_lps.md
Labels: ac-code-remediation
