Repository vegaprotocol/specs, pull requests merged in 2023-08, with the labels that each got.

#1865 feat: update "cosmicelevator" ac
  protocol/0031-ETHB-ethereum_bridge_spec.md
  protocol/0040-ASSF-asset_framework.md
  protocol/0045-DSRC-data_sourcing.md
  protocol/0047-DSRF-data_source_filter.md
  protocol/0048-DSRI-data_source_internal.md
  protocol/0055-TREA-on_chain_treasury.md
  protocol/0057-TRAN-transfers.md
  protocol/0062-SPAM-spam_protection.md
  protocol/0069-VCBS-validators_chosen_by_stake.md
  protocol/0072-SPPW-spam-protection-PoW.md
  protocol/0076-DANO-data-node.md
  protocol/features.json
Labels: ac-code-remediation

#1828 Closed market list changes
  user-interface/6001-MARK-find_markets.md
Labels: front-end-ac

#1468 chore: update data display for mark price, liquidation price and pnl
  user-interface/9001-DATA-data_display.md
Labels: front-end-ac

#1512 `DATA`. Quantum decimals and accounts
  user-interface/1002-WITH-withdraw.md
  user-interface/7002-SORD-submit_orders.md
  user-interface/9001-DATA-data_display.md
Labels: front-end-ac

#1857 chore: add acs for network upgrade proposal
  user-interface/3001-VOTE-vote.md
  user-interface/3002-PROP-propose.md
  user-interface/3003-PMAN-propose_new_market.md
  user-interface/3009-NTWU-network-upgrade.md
Labels: front-end-ac

#1875 chore: ethereum oracles acceptance criteria updates
  protocol/0028-GOVE-governance.md
  protocol/0082-ETHD-ethereum-data-source.md
  protocol/features.json
  wordlist.txt
Labels: ethereum-oracles

#1870 feat: adding perp spec copies
  protocol/0002-STTL-settlement.md
  protocol/0043-MKTL-market_lifecycle.md
  protocol/0051-PROD-product.md
  protocol/0070-MKTD-market-decimal-places.md
  protocol/0073-LIMN-limited_network_life.md
  protocol/features.json
Labels: product perpetuals

#1886 Successor market ac007
  protocol/0081-SUCM-successor_markets.md
Labels: ac-code-remediation

#1891 refactor: clarify parameter and variable terms
  protocol/0083-RFPR-on_chain_referral_program.md
  protocol/0084-VDPR-volume_discount_program.md
Labels: referral

#1894 chore: update successor market ACs and the feature linkings
  protocol/0081-SUCM-successor_markets.md
  protocol/features.json
Labels: ac-code-remediation, successor-markets

#1905 refactor: update 0070-MKTD-007
  protocol/0070-MKTD-market-decimal-places.md
Labels: liquidity-sla

#1909 refactor: clarify network parameter behaviour for referral and volume discount programs
  protocol/0083-RFPR-on_chain_referral_program.md
  protocol/0084-VDPR-volume_discount_program.md
  protocol/features.json
Labels: referral

#1902 During a recurring transfer fund the source account and ensure extra tokens are distributed
  protocol/0028-GOVE-governance.md
  protocol/features.json
Labels: governance

#1876 feat: rewards overhaul
  protocol/0056-REWA-rewards_overview.md
  protocol/0057-TRAN-transfers.md
  protocol/0083-RFPR-on_chain_referral_program.md
  protocol/0085-RVST-rewards_vesting.md
  protocol/0086-ASPR-activity_streak_program.md
  wordlist.txt
Labels: referral, rewards

#1906 feat: added Acceptance Criteria for Liquidity Provisioning
  protocol/0044-LIME-lp_mechanics.md
  protocol/features.json
Labels: liquidity-sla

#1920 chore: Delete incorrect acceptance criteria
  protocol/0082-ETHD-ethereum-data-source.md
  protocol/features.json
Labels: product perpetuals, ethereum-oracles

#1921 Ac 0034 update
  protocol/0034-PROB-prob_weighted_liquidity_measure.ipynb
Labels: spec-improvement
