Repository vegaprotocol/specs, pull requests merged in 2023-09, with the labels that each got.

#1924 fix: Fix features.json
  protocol/features.json
Labels: ac-code-remediation

#1925 Update 0044-LIME-lp_mechanics.md
  protocol/0044-LIME-lp_mechanics.md
Labels: ac-code-remediation

#1927 Update AC 0044-LIME-028: iceberg liquidity commitment
  protocol/0044-LIME-lp_mechanics.md
Labels: enhancement, specs

#1926 chore: add two eth oracles ACs related to multiple contracts
  protocol/0082-ETHD-ethereum-data-source.md
  protocol/features.json
Labels: ethereum-oracles

#1929 chore: Update features.json
  protocol/features.json
Labels: ac-code-remediation

#1898 More sla acs
  protocol/0026-AUCT-auctions.md
  protocol/0042-LIQF-setting_fees_and_rewarding_lps.md
  protocol/0044-LIME-lp_mechanics.md
  protocol/features.json
Labels: spec-bug, ac-code-remediation, liquidity-sla

#1923 fix: reword ACs 38, 39
  protocol/0082-ETHD-ethereum-data-source.md
Labels: specs, ethereum-oracles

#1931 fix: Spot ACs in features.json file
  protocol/features.json
Labels: ac-code-remediation

#1932 0044 026
  protocol/0044-LIME-lp_mechanics.md
Labels: enhancement

#1933 fix: Minor spelling corrections, plus two new ACs for testing perp da…
  protocol/0001-MKTF-market_framework.md
  protocol/0053-PERP-product_builtin_perpetual_future.md
  protocol/features.json
Labels: product perpetuals

#1947 chore: add AC codes to referral ACs in fees spec
  protocol/0029-FEES-fees.md
  protocol/features.json
Labels: ac-code-remediation

#1948 chore: move batch transfers out of deployment 2
  protocol/features.json
Labels: ac-code-remediation

#1939 feat: align 0042-LIQF-053 with core implementation
  protocol/0042-LIQF-setting_fees_and_rewarding_lps.md
Labels: ac-code-remediation

#1938 feat: add acceptance criteria for reward vesting and activity streaks
  protocol/0085-RVST-rewards_vesting.md
  protocol/0086-ASPR-activity_streak_program.md
  protocol/features.json
Labels: ac-code-remediation, referral, rewards

#1953 feat: add clarification when no indicative price
  protocol/0044-LIME-lp_mechanics.md
Labels: spec-improvement

#1916 Update 0044-LIME-lp_mechanics.md
  protocol/0044-LIME-lp_mechanics.md
Labels: ac-code-remediation

#1965 Small clarifications
  non-protocol-specs/0012-NP-LIPE-liquidation-price-estimate.md
  protocol/0053-PERP-product_builtin_perpetual_future.md
  protocol/features.json
Labels: product perpetuals, ac-code-remediation

#1962 feat: add additional referral program test ACs
  protocol/0029-FEES-fees.md
  protocol/0083-RFPR-on_chain_referral_program.md
  protocol/features.json
Labels: ac-code-remediation, referral

#1972 chore: rename closing_timestamp to end_of_program_timestamp
  protocol/0083-RFPR-on_chain_referral_program.md
  protocol/0084-VDPR-volume_discount_program.md
Labels: spec-improvement, referral

#1973 chore: update GOVE-140 to clarify reward account types
  protocol/0028-GOVE-governance.md
Labels: ac-code-remediation

#1967 chore: Update eth oracle acceptance criteria
  protocol/0082-ETHD-ethereum-data-source.md
Labels: ac-code-remediation, ethereum-oracles

#1977 chore: correct AC typo in volume discount spec
  protocol/0083-RFPR-on_chain_referral_program.md
  protocol/0084-VDPR-volume_discount_program.md
Labels: spec-improvement

#1982 Update features.json to align milestone names
  protocol/features.json
Labels: ac-code-remediation
