Repository vegaprotocol/specs, pull requests merged in 2023-11, with the labels that each got.

#2020 feat: fixed size order amendments
  protocol/0004-AMND-amends.md
  protocol/features.json
Labels: orders

#2030 chore: tidy up the features.json for palazzo milestone
  protocol/cosmic-features.json
  protocol/features.json
Labels: ac-code-remediation

#2039 chore: add AC's for liquidity fee setting methods
  protocol/0042-LIQF-setting_fees_and_rewarding_lps.md
  protocol/features.json
Labels: liquidity

#2033 feat: updates for transfers from vested accounts
  protocol/0057-TRAN-transfers.md
  protocol/0085-RVST-rewards_vesting.md
  protocol/features.json
Labels: rewards

#2001 Perps: modify funding payment calculation
  protocol/0053-PERP-product_builtin_perpetual_future.md
  protocol/features.json
  wordlist.txt
Labels: product perpetuals

#2041 chore: add ACs to features.json from transfer fee improvements
  protocol/features.json
Labels: ac-code-remediation

#2044 Default value fee discount num of epoch
  protocol/0057-TRAN-transfers.md
Labels: spec-improvement

#2046 feat: update AC 0019-MCAL-030
  protocol/0019-MCAL-margin_calculator.md
  protocol/features.json
Labels: ac-code-remediation

#2049 feat: update margin example in 0019
  protocol/0019-MCAL-margin_calculator.md
Labels: specs

#2051 refactor: clarify AC 0057-TRAN-069
  protocol/0057-TRAN-transfers.md
Labels: ac-code-remediation

#2056 fix: add ac - quantum updates on enactment
  protocol/0027-ASSP-asset_proposal.md
Labels: ac-code-remediation, assets

#2055 feat: isolated margin tweaks
  protocol/0019-MCAL-margin_calculator.md
  wordlist.txt
Labels: margins

#2054 Ac isolated margin
  protocol/0019-MCAL-margin_calculator.md
  protocol/features.json
Labels: ac-code-remediation

#2057 Transfer fee (Spec 0057) AC update
  protocol/0057-TRAN-transfers.md
  protocol/features.json
Labels: ac-code-remediation

#2060 feat: rename network parameter FeeDiscountDecay
  protocol/0057-TRAN-transfers.md
Labels: spec-improvement

#2062 Governance proposal market name
  protocol/0028-GOVE-governance.md
Labels: spec-improvement

#2064 chore: add ACs to features file for overnance proposal market name
  protocol/features.json
Labels: ac-code-remediation

#2065 Insurance pools of closed / settled markets to go to on - chain treasury
  protocol/0002-STTL-settlement.md
  protocol/0013-ACCT-accounts.md
  protocol/0015-INSR-market_insurance_pool_collateral.md
  protocol/0043-MKTL-market_lifecycle.md
  protocol/0073-LIMN-limited_network_life.md
  protocol/0081-SUCM-successor_markets.md
  protocol/features.json
Labels: spec-improvement

#2067 feat: add more ACs to isolated margin
  protocol/0019-MCAL-margin_calculator.md
  protocol/features.json
Labels: spec-improvement

#2069 feat: add more ACs for isolated-margin
  protocol/0019-MCAL-margin_calculator.md
  protocol/features.json
Labels: spec-improvement
