Repository vegaprotocol/specs, pull requests merged in 2023-05, with the labels that each got.

#1657 Add UI spec for current functionality of fills
  user-interface/7005-FILL-fills.md
Labels: front-end-ac

#1656 Add UI spec for current functionality surrounding collateral
  user-interface/6501-ASSE-assets.md
  user-interface/7001-COLL-collateral.md
Labels: front-end-ac

#1496 feat: builtin product Spot
  protocol/0041-TSTK-target_stake.md
  protocol/0080-SPOT-product_builtin_spot.md
Labels: spot

#1700 0006-NETW
  user-interface/0006-NETW-network-and-nodes.md
Labels: front-end-ac

#1704 Fix/succesor markets
  protocol/0001-MKTF-market_framework.md
  protocol/0015-INSR-market_insurance_pool_collateral.md
  protocol/0028-GOVE-governance.md
  wordlist.txt
Labels: successor-markets

#1713 feat: typo in spec estimate position
  non-protocol-specs/0012-NP-LIPE-liquidation-price-estimate.md
Labels: ac-code-remediation

#1717 chore: update spec for governance transfers to include more details a…
  protocol/0028-GOVE-governance.md
Labels: governance

#1725 chore: withdraw minimal amount
  spellcheck.sh
  user-interface/1002-WITH-withdraw.md
Labels: front-end-ac

#1694 feat: align Spot product with SLA changes
  protocol/0080-SPOT-product_builtin_spot.md
Labels: spot
