Repository vegaprotocol/specs, pull requests merged in 2023-07, with the labels that each got.

#1804 feat: use ghcr image to run approbation
  .github/workflows/quality_check.yml
Labels: task::implement

#1803 Clarify gov transfer AC
  protocol/0028-GOVE-governance.md
Labels: ac-code-remediation

#1802 chore(trading): fix spec links
  user-interface/0006-NETW-network-and-nodes.md
  user-interface/1003-TRAN-transfer.md
  user-interface/6004-CHAR-chart.md
  user-interface/6006-DEPC-chart_depth.md
  user-interface/6007-CHAR-chart.md
  user-interface/7004-POSI-positions.md
  user-interface/README.md
  user-interface/apps.json
  user-interface/categories.json
Labels: front-end-ac

#1801 Update ACs for proposals via governance
  protocol/0028-GOVE-governance.md
Labels: ac-code-remediation

#1805 Update 0044 sla spec1
  protocol/0044-LIME-lp_mechanics.md
Labels: liquidity-sla

#1789 Fix broken link in 0028-GOVE
  protocol/0028-GOVE-governance.md
Labels: spec-bug

#1806 Include stop orders in gas calculations
  protocol/0078-NWLI-network_wide_limits.md
  protocol/0079-TGAP-transaction_gas_and_priority.md
Labels: orders

#1807 New successor acs
  protocol/0081-SUCM-successor_markets.md
Labels: ac-code-remediation, successor-markets

#1793 Fix/sla details on where penalties go
  protocol/0044-LIME-lp_mechanics.md
Labels: liquidity-sla

#1808 Small changes to various specs
  protocol/0028-GOVE-governance.md
  protocol/0043-MKTL-market_lifecycle.md
  protocol/0055-TREA-on_chain_treasury.md
  protocol/0073-LIMN-limited_network_life.md
  protocol/0081-SUCM-successor_markets.md
Labels: spec-improvement

#1791 feat: add ACs for Spot market
  protocol/0004-AMND-amends.md
  protocol/0008-TRAD-trading_workflow.md
  protocol/0009-MRKP-mark_price.md
  protocol/0011-MARA-check_order_allocate_margin.md
  protocol/0013-ACCT-accounts.md
  protocol/0014-ORDT-order_types.md
  protocol/0017-PART-party.md
  protocol/0020-APIS-core_api.md
  protocol/0021-MDAT-market_data_spec.md
  protocol/0024-OSTA-order_status.md
  protocol/0025-OCRE-order_submission.md
  protocol/0026-AUCT-auctions.md
  protocol/0027-ASSP-asset_proposal.md
  protocol/0029-FEES-fees.md
  protocol/0032-PRIM-price_monitoring.md
  protocol/0033-OCAN-cancel_orders.md
  protocol/0034-PROB-prob_weighted_liquidity_measure.ipynb
  protocol/0037-OPEG-pegged_orders.md
  protocol/0039-MKTD-market_depth_calculation.md
  protocol/0043-MKTL-market_lifecycle.md
  protocol/0045-DSRC-data_sourcing.md
  protocol/0046-DSRM-data_source_signed_message.md
  protocol/0047-DSRF-data_source_filter.md
  protocol/0048-DSRI-data_source_internal.md
  protocol/0049-TVAL-validate_transaction_preconsensus.md
  protocol/0050-EPOC-epochs.md
  protocol/0051-PROD-product.md
  protocol/0052-FPOS-fractional_orders_positions.md
  protocol/0054-NETP-network_parameters.md
  protocol/0055-TREA-on_chain_treasury.md
  protocol/0056-REWA-rewards_overview.md
  protocol/0057-TRAN-transfers.md
  protocol/0061-REWP-pos_rewards.md
  protocol/0063-VALK-validator_vega_master_keys.md
  protocol/0064-VALP-validator_performance_based_rewards.md
  protocol/0065-FTCO-floating_point_consensus.md
  protocol/0068-MATC-matching_engine.md
  protocol/0069-VCBS-validators_chosen_by_stake.md
  protocol/0070-MKTD-market-decimal-places.md
  protocol/0073-LIMN-limited_network_life.md
  protocol/0074-BTCH-batch-market-instructions.md
  protocol/0075-PLUP-protocol_upgrades.md
  protocol/0076-DANO-data-node.md
  protocol/0077-SNAP-snapshots.md
  protocol/0079-TGAP-transaction_gas_and_priority.md
  protocol/0080-SPOT-product_builtin_spot.md
Labels: spot, ac-code-remediation

#1833 Add sla acs 1
  protocol/0044-LIME-lp_mechanics.md
Labels: liquidity-sla

#1835 chore: update spot ACs after 1st QA review
  protocol/0074-BTCH-batch-market-instructions.md
  protocol/0080-SPOT-product_builtin_spot.md
  protocol/features.json
Labels: spot, ac-code-remediation

#1814 refactor: update spot parameters
  protocol/0080-SPOT-product_builtin_spot.md
Labels: spot

#1846 Update the features.json
  protocol/features.json
Labels: ac-code-remediation

#1837 Update sla acs 1
  protocol/0044-LIME-lp_mechanics.md
  protocol/features.json
Labels: spot, liquidity-sla

#1852 Update sla acs 2 - acs for new api
  protocol/0042-LIQF-setting_fees_and_rewarding_lps.md
  protocol/0044-LIME-lp_mechanics.md
  protocol/features.json
Labels: liquidity-sla

#1826 Update 0036-BRIE-event_queue.md
  protocol/0036-BRIE-event_queue.md
Labels: spec-improvement

#1811 fix: update links to legacy spec 0038-OLIQ
  non-protocol-specs/0001-NP-LIQB-liquidity_providing_bots.md
  protocol/0013-ACCT-accounts.md
  protocol/0017-PART-party.md
  protocol/0021-MDAT-market_data_spec.md
  protocol/0026-AUCT-auctions.md
  protocol/0028-GOVE-governance.md
  protocol/0042-LIQF-setting_fees_and_rewarding_lps.md
  protocol/0043-MKTL-market_lifecycle.md
  protocol/0044-LIME-lp_mechanics.md
  protocol/0052-FPOS-fractional_orders_positions.md
  protocol/0073-LIMN-limited_network_life.md
  protocol/0078-NWLI-network_wide_limits.md
  protocol/README.md
Labels: spec-bug, ac-code-remediation

#1859 stop orders acs
  user-interface/7002-SORD-submit_orders.md
Labels: front-end-ac

#1863 chore: update features.json
  protocol/features.json
Labels: ac-code-remediation

#1855 Markets in suspension can be resumed or terminated after a protocol u…
  protocol/0028-GOVE-governance.md
  protocol/features.json
Labels: 🏪 Market Governance

#1869 fix: new LPs committing liquidity / existing LPs increasing
  protocol/0044-LIME-lp_mechanics.md
Labels: spec-bug
