Repository vegaprotocol/specs, pull requests merged in 2023-06, with the labels that each got.

#1738 SLA liquidity (extras)
  glossaries/trading-and-protocol-glossary.md
  protocol/0013-ACCT-accounts.md
  protocol/0014-ORDT-order_types.md
  protocol/0039-MKTD-market_depth_calculation.md
  protocol/0041-TSTK-target_stake.md
  protocol/0044-LIME-lp_mechanics.md
  user-interface/7003-MORD-manage_orders.md
Labels: liquidity-sla

#1730 Update 0028-GOVE-governance.md
  protocol/0028-GOVE-governance.md
Labels: governance

#1722 Added all markets and proposal markets ACs
  user-interface/6001-MARK-find_markets.md
Labels: front-end-ac

#1749 Fix formula + small clarification
  protocol/0044-LIME-lp_mechanics.md
Labels: liquidity-sla

#1733 chore(trading): Add Position ACs
  user-interface/7004-POSI-positions.md
Labels: front-end-ac

#1754 feat: add new ACs from the AC review meeting
  protocol/0081-SUCM-successor_markets.md
Labels: ac-code-remediation, successor-markets

#1747 chore: add decision about market-depth with regard to iceberg orders
  protocol/0014-ORDT-order_types.md
Labels: orders

#1741 Update 0028-GOVE-governance.md 0028-GOVE-076
  protocol/0028-GOVE-governance.md
Labels: governance

#1748 5002-LIQP - Liquidity ACs
  user-interface/5002-LIQP-liquidity.md
  user-interface/5002-LIQP-provide_liquidity.md
Labels: front-end-ac

#1763 chore: Remove invalid ac relating to minimum order size
  protocol/0014-ORDT-order_types.md
Labels: ac-code-remediation

#1764 refactor: clarify iceberg wash trading AC
  protocol/0014-ORDT-order_types.md
Labels: ac-code-remediation

#1765 Update console space
  user-interface/apps.json
Labels: front-end-ac

#1767 chore: tidy up spec feature heading text
  protocol/0028-GOVE-governance.md
Labels: spec-improvement

#1766 chore: remove cosmic feature from master
  protocol/0028-GOVE-governance.md
Labels: spec-improvement

#1614 Add market closure governance proposal
  protocol/0028-GOVE-governance.md
  protocol/0043-MKTL-market_lifecycle.md
  wordlist.txt
Labels: product perpetuals, governance

#1720 chore(governance): update proposal acs
  user-interface/3001-VOTE-vote.md
  user-interface/3002-PROP-propose.md
  user-interface/3003-PMAN-propose_new_market.md
  user-interface/3004-PMAC-propose_market_change.md
  user-interface/3005-PASN-propose_new_asset.md
  user-interface/3006-PASC-propose_asset_change.md
  user-interface/3007-PNEC-propose_network.md
  user-interface/3008-PFRO-propose_freeform.md
Labels: front-end-ac

#1771 chore: 6005-THIS-trade_history filled with ACs
  user-interface/6005-THIS-trade_history.md
Labels: front-end-ac

#1774 fix: clarify what's a market and what's a network param.
  protocol/0041-TSTK-target_stake.md
Labels: spec-improvement

#1770 fix: Remove GOVE-095 AC as it seemingly contradicts spec itself
  protocol/0028-GOVE-governance.md
Labels: governance

#1776 add browser wallet loading state ACs
  user-interface/1101-BWAL-browser_wallet.md
Labels: front-end-ac

#1772 popout windoiw
  user-interface/1101-BWAL-browser_wallet.md
Labels: front-end-ac

#1777 Fix: SUCM netparam not market param
  protocol/0081-SUCM-successor_markets.md
Labels: successor-markets

#1769 Update 5002-LIQP-liquidity.md with 5002-LIQP-013
  user-interface/5002-LIQP-liquidity.md
Labels: front-end-ac

#1784 depth chart ACs
  user-interface/6006-DEPC-chart_depth.md
  user-interface/apps.json
Labels: front-end-ac

#1783 chore: Add more acceptance criteria for Stop Orders
  protocol/0014-ORDT-order_types.md
Labels: orders

#1786 Add ACs for Gov Transfer cancellation proposal/network history restore/split permitted combos into ACs
  protocol/0028-GOVE-governance.md
Labels: ac-code-remediation

#1781 re-arrange ac to save mainetenance
  user-interface/1101-BWAL-browser_wallet.md
  user-interface/1101-ONBD-onboarding.md
  user-interface/1102-LGIN-login.md
  user-interface/1103-CONN-connect_to_wallet.md
  user-interface/1104-DCON-disconnect_wallet.md
  user-interface/1105-TRAN-transactions.md
  user-interface/1106-KEYS-wallet_and_keys.md
  user-interface/1107-SETT-settings.md
  user-interface/1108-NTWK-network.md
  user-interface/1109-VCON-view_connections.md
  user-interface/1110-RMST-remember_state.md
  user-interface/apps.json
  user-interface/categories.json
Labels: front-end-ac

#1758 Update 0080-SPOT-product_builtin_spot.md
  protocol/0080-SPOT-product_builtin_spot.md
Labels: spec-bug

#1792 Add LP mechanics ACs 27-32 - Snapshots, Checkpoints, qualifying order types and others
  protocol/0044-LIME-lp_mechanics.md
Labels: liquidity-sla

#1790 Gov transfers - Snapshots, Checkpoints, PULP and other missing ACs
  protocol/0028-GOVE-governance.md
Labels: governance

#1794 update spec for parent in proposed state
  protocol/0081-SUCM-successor_markets.md
Labels: successor-markets

#1775 chore(trading): 6004-CHAR-chart ACs created
  user-interface/6004-CHAR-chart.md
  user-interface/6004-PHIS-price_history.md
Labels: front-end-ac, do-not-merge

#1797 Add network history AC 0044 sla spec
  protocol/0044-LIME-lp_mechanics.md
Labels: ac-code-remediation, liquidity-sla

#1796 fix: correction on amending commitment
  protocol/0044-LIME-lp_mechanics.md
Labels: spec-improvement, liquidity-sla

#1798 Revert "Add network history AC 0044 sla spec"
  protocol/0044-LIME-lp_mechanics.md
Labels: liquidity-sla

#1799 Revert "Add LP mechanics ACs 27-32 - Snapshots, Checkpoints, qualifying order types and others"
  protocol/0044-LIME-lp_mechanics.md
Labels: liquidity-sla

#1787 feat: Update stop spec ACs
  protocol/0014-ORDT-order_types.md
Labels: spot, ac-code-remediation
