Repository vegaprotocol/specs, pull requests merged in 2023-03, with the labels that each got.

#1604 Update 0069-VCBS-validators_chosen_by_stake.md
  protocol/0069-VCBS-validators_chosen_by_stake.md
Labels: ac-code-remediation

#1600 refactor: add slippage to orders
  protocol/0010-MARG-margin_orchestration.md
  protocol/0019-MCAL-margin_calculator.md
Labels: ac-code-remediation

#1601 fix: More validator join/leave test cases involving checkpoints.
  protocol/0069-VCBS-validators_chosen_by_stake.md
Labels: ac-code-remediation

#1605 feat: update make file and add approabtion to CI
  .github/workflows/quality_check.yml
  makefile
  protocol/0042-LIQF-setting_fees_and_rewarding_lps.md
  protocol/0069-VCBS-validators_chosen_by_stake.md
Labels: ac-code-remediation

#1609 feat: fix typo in 0042
  protocol/0042-LIQF-setting_fees_and_rewarding_lps.md
Labels: specs, ac-code-remediation

#1603 fix: Relabel existing PLUP mainnet case to reflect the fact that it i…
  protocol/0075-PLUP-protocol_upgrades.md
Labels: ac-code-remediation

#1618 chore: Amend acceptance criteria to cosmic elevator
  non-protocol-specs/0011-NP-CLIE-client-interaction-tests.md
Labels: ac-code-remediation

#1622 feat: add distressed status
  protocol/0007-POSN-non_core_positions_api.md
Labels: specs, spec-improvement

#1617 feat: update probability range in price monitoring
  protocol/0018-RSKM-quant_risk_models.ipynb
  protocol/0032-PRIM-price_monitoring.md
Labels: specs, spec-improvement

#1625 feat: post only orders
  protocol/0014-ORDT-order_types.md
  protocol/0068-MATC-matching_engine.md
Labels: ac-code-remediation

#1624 user-interface WTXN: remove some ACs that are Covered by block explorer
  user-interface/0003-WTXN-submit_vega_transaction.md
Labels: front-end-ac

#1623 user interface: Wallet: Remove requirement codes for things that have not been implemented
  user-interface/0001-WALL-wallet.md
Labels: front-end-ac

#1631 User interface: WTXN: add some clarifying text
  user-interface/0001-WALL-wallet.md
  user-interface/0003-WTXN-submit_vega_transaction.md
Labels: front-end-ac

#1636 chore: remove invalid and unimplemented use cases
  user-interface/0001-WALL-wallet.md
Labels: wallet

#1640 User interface: add Post only and Reduce only
  user-interface/7002-SORD-submit_orders.md
  user-interface/7003-MORD-manage_orders.md
Labels: front-end-ac

#1647 feat: update FOK MO reduce-only
  protocol/0068-MATC-matching_engine.md
Labels: spec-improvement
