Repository vegaprotocol/specs, pull requests merged in 2023-04, with the labels that each got.

#1671 fix: 005 AC code link
  protocol/0080-TBPM-time_based_pruning_mempool.md
Labels: ac-code-remediation

#1664 user interface: Can not destroy metamask session from dapp
  user-interface/0004-EWAL-connect_ethereum_wallet.md
Labels: front-end-ac

#1682 feat: update typo in 0061
  protocol/0061-REWP-pos_rewards.md
Labels: spec-improvement

#1683 feat: add explaination on ersatz validators
  protocol/0061-REWP-pos_rewards.md
  protocol/0069-VCBS-validators_chosen_by_stake.md
  protocol/0075-PLUP-protocol_upgrades.md
Labels: spec-improvement
