Repository vegaprotocol/specs, pull requests merged in 2023-12, with the labels that each got.

#2068 fix: formula in ac
  protocol/0053-PERP-product_builtin_perpetual_future.md
Labels: product perpetuals, ac-code-remediation

#2072 feat: tidy up and add more ACS
  protocol/0019-MCAL-margin_calculator.md
  protocol/features.json
Labels: margins, spec-improvement, ac-code-remediation

#2078 fix: update amend pegged order margin expected behaviour
  protocol/0019-MCAL-margin_calculator.md
Labels: margins, ac-code-remediation

#2080 feat: update for pegged order in isolated margin
  protocol/0019-MCAL-margin_calculator.md
  protocol/features.json
Labels: spec-change

#2082 feat: more margin pegged order acs
  protocol/0019-MCAL-margin_calculator.md
  protocol/features.json
Labels: ac-code-remediation

#2083 refactor: remove batch proposal ac 0028-GOVE-162
  protocol/0028-GOVE-governance.md
  protocol/features.json
Labels: ac-code-remediation

#2085 feat: update AC
  protocol/0019-MCAL-margin_calculator.md
  protocol/features.json
Labels: ac-code-remediation

#2086 feat: update market state when market name/code is changed while governance proposal
  protocol/0028-GOVE-governance.md
Labels: spec-improvement
