Repository vegaprotocol/specs, pull requests merged in 2023-10, with the labels that each got.

#1971 feat: add ACs for in-scope reward features
  protocol/0056-REWA-rewards_overview.md
  protocol/features.json
Labels: ac-code-remediation, rewards

#1985 chore: update 0070-MKTD-018 and 19 and add a new AC for exact precision
  protocol/0070-MKTD-market-decimal-places.md
Labels: ac-code-remediation

#1983 fix: remove specific time from the ACs
  protocol/0084-VDPR-volume_discount_program.md
Labels: ac-code-remediation

#1986 feat: add SLA edge case
  protocol/0044-LIME-lp_mechanics.md
Labels: liquidity-sla

#1992 Update 0028-GOVE-governance.md
  protocol/0028-GOVE-governance.md
Labels: ac-code-remediation

#2013 chore: update palazzo with change from PR 1992
  .github/workflows/quality_check.yml
  protocol/0028-GOVE-governance.md
  protocol/features.json
Labels: ac-code-remediation

#2018 feat: align discount application with core implementation
  protocol/0029-FEES-fees.md
  protocol/features.json
Labels: spec-bug, ac-code-remediation
