Repository vegaprotocol/specs, pull requests merged in 2024-04, with the labels that each got.

#2247 chore: tidy spot marginal cost acs
  protocol/0042-LIQF-setting_fees_and_rewarding_lps.md
  protocol/features.json
Labels: ac-code-remediation

#2250 feat: couple nice to have acs
  protocol/0074-BTCH-batch-market-instructions.md
  protocol/features.json
Labels: ac-code-remediation

#2241 feat: make relative return reward include losses
  protocol/0056-REWA-rewards_overview.md
  protocol/features.json
Labels: rewards

#2248 chore: remove invalid stop order AC for spot markets
  protocol/0014-ORDT-order_types.md
  protocol/features.json
Labels: ac-code-remediation

#2256 feat: add acceptance criteria for changing position size
  protocol/0056-REWA-rewards_overview.md
  protocol/features.json
Labels: ac-code-remediation

#2258 feat: couple more spot acs
  protocol/0028-GOVE-governance.md
  protocol/features.json
Labels: spot, ac-code-remediation

#1913 feat: add transfer interval field
  protocol/0057-TRAN-transfers.md
  protocol/features.json
Labels: rewards
