Repository vegaprotocol/specs, pull requests merged in 2024-01, with the labels that each got.

#2088 AC 0028-GOVE-160 - replace withdrawal limit > maximumLifetimeDeposit
  protocol/0028-GOVE-governance.md
Labels: ac-code-remediation

#2090 feat: update meaning of closed and allow_list team fields
  protocol/0083-RFPR-on_chain_referral_program.md
  protocol/features.json
  wordlist.txt
Labels: ac-code-remediation, spec-change

#2077 feat: add two system-test acs
  protocol/0019-MCAL-margin_calculator.md
  protocol/features.json
Labels: margins

#2095 feat: few acs for stop orders in auction
  protocol/0014-ORDT-order_types.md
  protocol/features.json
Labels: ac-code-remediation

#2096 feat: add acs for network profit and loss
  protocol/0012-POSR-position_resolution.md
  protocol/features.json
Labels: ac-code-remediation, liquidation

#2102 chore: add AC code to existing AC
  protocol/0083-RFPR-on_chain_referral_program.md
  protocol/features.json
Labels: ac-code-remediation

#2107 feat: add validation ac for mark price
  protocol/0009-MRKP-mark_price.md
Labels: spec-improvement

#2112 feat: add AC 126
  protocol/0009-MRKP-mark_price.md
Labels: spec-improvement

#2110 chore: Add more perps funding ACs
  protocol/0053-PERP-product_builtin_perpetual_future.md
  protocol/0082-ETHD-ethereum-data-source.md
  protocol/features.json
Labels: ac-code-remediation

#2113 fix: add missing AC codes to the featurews.json file
  protocol/features.json
Labels: ac-code-remediation

#2115 chore: Add ACs from the LP fee setting AC review meeting
  protocol/0042-LIQF-setting_fees_and_rewarding_lps.md
  protocol/features.json
Labels: liquidity, ac-code-remediation

#2120 chore: comment out the cosmic-carryover
  protocol/cosmic-features.json
  protocol/features.json
Labels: ac-code-remediation

#2111 fix: correct the AC requirement to match the correct behaviour
  protocol/0019-MCAL-margin_calculator.md
  protocol/features.json
Labels: ac-code-remediation

#2114 feat: more validation acs
  protocol/0009-MRKP-mark_price.md
  protocol/features.json
Labels: ac-code-remediation

#2123 chore: update features.json
  protocol/features.json
Labels: ac-code-remediation

#2126 chore: split AC code 0009-MRKP-056 into 3
  protocol/0009-MRKP-mark_price.md
  protocol/features.json
Labels: ac-code-remediation

#2125 chore: adds AC from the isolated margin AC review
  protocol/0019-MCAL-margin_calculator.md
  protocol/features.json
Labels: ac-code-remediation

#2127 chore Update features.json to add missing AC code
  protocol/features.json
Labels: ac-code-remediation

#2128 chore: add AC thats pushed from palazzo milestone
  protocol/nebula-features.json
Labels: ac-code-remediation

#2109 chore: add more position stop order AC codes
  protocol/0014-ORDT-order_types.md
  protocol/features.json
Labels: ac-code-remediation

#2131 Add AC003 to mark price spec
  protocol/0009-MRKP-mark_price.md
  protocol/features.json
Labels: spec-improvement

#2132 feat: update ac 027 (mark price when exiting auction)
  protocol/0009-MRKP-mark_price.md
Labels: spec-improvement

#2134 feat: change tau scaling bound
  protocol/0034-PROB-prob_weighted_liquidity_measure.ipynb
  protocol/0042-LIQF-setting_fees_and_rewarding_lps.md
Labels: spec-improvement

#2135 chore: descope AC 0053-PERP-035 from Palazzo
  protocol/0053-PERP-product_builtin_perpetual_future.md
  protocol/features.json
Labels: ac-code-remediation

#2137 Updating AC to cover wrong side stop orders being rejected
  protocol/0014-ORDT-order_types.md
Labels: ac-code-remediation

#2139 feat: add ac for price available via data node
  protocol/0009-MRKP-mark_price.md
  protocol/0053-PERP-product_builtin_perpetual_future.md
  protocol/features.json
Labels: spec-improvement

#2140 chore: remove ACs from palazzo
  protocol/features.json
Labels: ac-code-remediation

#2141 chore: update ACs moved from palazzo to nebula
  protocol/0009-MRKP-mark_price.md
  protocol/0053-PERP-product_builtin_perpetual_future.md
  protocol/nebula-features.json
Labels: ac-code-remediation
