Repository vegaprotocol/specs, pull requests merged in 2024-03, with the labels that each got.

#2191 feat: cancel pegged orders when updating tick size
  protocol/0028-GOVE-governance.md
  protocol/features.json
Labels: spec-bug

#2203 chore: fix AC typo in pegged order spec
  protocol/0037-OPEG-pegged_orders.md
Labels: spec-bug

#2194 Wording for iceberg testing
  protocol/0014-ORDT-order_types.md
Labels: spot

#2207 Add ac for 0019 mcal 208 to features file
  protocol/features.json
Labels: ac-code-remediation

#2146 feat: removal of checkpoint
  protocol/0028-GOVE-governance.md
  protocol/0036-BRIE-event_queue.md
  protocol/0040-ASSF-asset_framework.md
  protocol/0044-LIME-lp_mechanics.md
  protocol/0053-PERP-product_builtin_perpetual_future.md
  protocol/0054-NETP-network_parameters.md
  protocol/0056-REWA-rewards_overview.md
  protocol/0063-VALK-validator_vega_master_keys.md
  protocol/0067-KEYS-key_management.md
  protocol/0069-VCBS-validators_chosen_by_stake.md
  protocol/0073-LIMN-limited_network_life.md
  protocol/0075-PLUP-protocol_upgrades.md
  protocol/0077-SNAP-snapshots.md
  protocol/0081-SUCM-successor_markets.md
  protocol/0082-ETHD-ethereum-data-source.md
  protocol/categories.json
Labels: 💀 Limited Network Life

#2210 Update price trigger limit from 5 to 100
  protocol/0032-PRIM-price_monitoring.md
Labels: no-code-required, spec-change

#2212 chore: remove 0043-MKTL-005
  protocol/0043-MKTL-market_lifecycle.md
  protocol/features.json
Labels: ac-code-remediation

#2213 Update 0024 osta 044
  protocol/0024-OSTA-order_status.md
Labels: ac-code-remediation

#2215 fix: Updating wording for self trading states
  protocol/0068-MATC-matching_engine.md
Labels: enhancement, no-code-required

#2217 fix: remove 0044-LIME-074 as its not for spot
  protocol/0044-LIME-lp_mechanics.md
  protocol/features.json
Labels: ac-code-remediation

#2220 Add ac for rewards.team.min epochs in team netparam
  protocol/0083-RFPR-on_chain_referral_program.md
  protocol/features.json
Labels: ac-code-remediation

#2221 chore: Add AC for vega issue #10973
  protocol/0043-MKTL-market_lifecycle.md
  protocol/features.json
Labels: ac-code-remediation

#2222 fix: update ac description
  protocol/0043-MKTL-market_lifecycle.md
Labels: ac-code-remediation

#2218 Feat/liq strat range
  protocol/0012-POSR-position_resolution.md
  protocol/features.json
  protocol/palazzo-features.json
  wordlist.txt
Labels: liquidity

#2219 feat: update spot spec with palazzo and colosseo features
  protocol/0014-ORDT-order_types.md
  protocol/0041-TSTK-target_stake.md
  protocol/0042-LIQF-setting_fees_and_rewarding_lps.md
  protocol/0044-LIME-lp_mechanics.md
  protocol/0080-SPOT-product_builtin_spot.md
  protocol/features.json
Labels: spot

#2224 chore(refactor): reorder features.json file
  protocol/features.json
Labels: ac-code-remediation
